spring:
  datasource:
    url: jdbc:postgresql://dpg-d0elu5adbo4c738qgn90-a.oregon-postgres.render.com/resto_postgresql_tdc
    username: resto_postgresql_tdc_user
    password: 8c5LmxuQtdSQduqyw59Kr1RqsNvk9y29
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        ejb :
          interceptor: com.mystock.mygestock.interceptor.Interceptor


    auditing:
      enabled: true
      dateTimeProvider: org.springframework.data.jpa.repository.support.JpaAuditingDateTimeProvider

logging:
  level:
    org:
      springframework:
        security: DEBUG

flickr:
  apiKey: a74ab48d977815f07703b6d3f2ee97b9
  apiSecret: 8cf703528d5c218b
  appKey: 72157720876486896-cee34375d2b207c0
  appSecret: 9da854192e7d214c

application:
  name: table-du-chef
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8085
  servlet:
    context-path: /api

postgresql://resto_postgresql_tdc_user:8c5LmxuQtdSQduqyw59Kr1RqsNvk9y29@dpg-d0elu5adbo4c738qgn90-a:
  oregon-postgres:
    render:
      com/resto_postgresql_tdc:
#    postgresql://resto_postgresql_tdc_user:8c5LmxuQtdSQduqyw59Kr1RqsNvk9y29@dpg-d0elu5adbo4c738qgn90-a:
#      oregon-postgres:
#        render:
#          com/resto_postgresql_tdc:
#            PGPASSWORD=8c5LmxuQtdSQduqyw59Kr1RqsNvk9y29 psql -h dpg-d0elu5adbo4c738qgn90-a.oregon-postgres.render.com -U resto_postgresql_tdc_user resto_postgresql_tdc
#





